### ISSUE TITLE
Could not find executable pandoc-include

### ISSUE THREAD

**Issue by espetro** [DCsunset/pandoc-include#1]
Hey @DCsunset ,

Thanks for this cool Pandoc feature. While trying it on Windows 10, running `pandoc paper.md --filter pandoc-include -o output.pdf` gives me:

```bash
Error running filter pandoc-include:
Could not find executable pandoc-include
```

My `paper.md` file follows the same syntax as the example provided, although it seems a binary problem. If I search the other Pandoc filters I use, they're all in the `Scripts/` folder inside Anaconda. However, I cannot find `pandoc-include`.

```cmd
where pandoc-*
...\Anaconda3\Scripts\pandoc-citeproc.exe
...\Anaconda3\Scripts\pandoc-eqnos.exe
...\Anaconda3\Scripts\pandoc-fignos.exe
...\Anaconda3\Scripts\pandoc-tablenos.exe
```

Any ideas? Thanks in advance!

**Comment by DCsunset** [comment]
Hi @espetro ,

Since this script is written in python, it doesn't have a binary file. Instead, it uses Python to execute the script.
So do you install the filter using pip and have Python installed?

**Comment by ikalogic** [comment]
Hi,

I have exactly the same problem.

I did install the script using pip and I have pytton installed...

**Comment by DCsunset** [comment]
@ikalogic Could you provide your pip version and list the directory where pandoc-include is installed?

**Comment by ikalogic** [comment]
Thank you very much for your quick response!

here is what i find:

```
C:\Windows\System32>pip -V
pip 19.2.2 from c:\python37\lib\site-packages\pip (python 3.7)

C:\Windows\System32>where pandoc-*
C:\Program Files\Pandoc\pandoc-citeproc.exe
```

Doing manual search, I find pandoc-include.exe somewhere in my user/roaming/ directory... I'll try to copy paste it in the same folder as pandoc and see what happens

**Comment by ikalogic** [comment]
Yup! that fixed it, i just had to copy/paste pandoc-include.exe in the same directory as pandoc, that is, here: 
`C:\Program Files\Pandoc`

Thanks!
