### ISSUE TITLE
Include support for bibliography

### ISSUE THREAD

**Issue by Gjacquenot** [DCsunset/pandoc-include#14]
Pandoc now allows native support for bibliography. However when a citation is made inside an included document, the citation is not rendered.

Is it possible to add support for bibliography ?

```bash
pandoc --citeproc --bibliography=doc.bib  main.md --filter pandoc-include -o main.html
```

with `main.md`

```md
# Hello world

!include chap01.md

## References

::: {#refs}
:::
```

with `chap01.md`

```md
# Chapter 1

[@MyBibliographicRef]
```

**Comment by DCsunset** [comment]
The pandoc command-line options are processed in order.
Therefore `--citeproc` and `--bibliography=doc.bib` should be placed after `--filter pandoc-include` to let it process the reference in `chap01.md`.

The command should be

```
pandoc main.md --filter pandoc-include --citeproc --bibliography=doc.bib -o main.html
```

**Comment by Gjacquenot** [comment]
Thanks for the answer.

Maybe, it is worthy to mention that option order is important in the main Readme.md and give this bibliogrpahic example?

**Comment by DCsunset** [comment]
Thanks for your suggestion. I will add it to the Readme soon.
