### ISSUE TITLE
Possible to use within code blocks?

### ISSUE THREAD

**Issue by dmalan** [DCsunset/pandoc-include#15]
Just wanted to ask if there's a way (or alternative syntax) to use `pandoc-include` to process include statements within code blocks, a la the below?

    ```c
    !include foo.c
    ```

We noticed that, by default, the above simple outputs `!include foo.c` literally, as via:

```html
<div class="sourceCode" id="cb3"><pre class="sourceCode c"><code class="sourceCode c"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>!include foo.c</span></code></pre>
```

Many thanks!

**Comment by DCsunset** [comment]
It sounds like a good suggestion. I will try to add this feature in the future.

**Comment by dmalan** [comment]
Thanks very much!

**Comment by DCsunset** [comment]
I have added code include in v0.8.5. I hope it could solve this issue.

**Comment by dmalan** [comment]
Working well! Thank you very much!
