### ISSUE TITLE
Shared library error

### ISSUE THREAD

**Issue by rien333** [DCsunset/pandoc-include#2]
Whenever I run pandoc with  `--filter pandoc-include` I get an error about a shared library:

```bash
$ cat test.md | pandoc --filter pandoc-include
pandoc-include: error while loading shared libraries: libHSpandoc-types-1.17.5.1-8DdN87tlyJbAzvpbzH68uw-ghc8.4.3.so: cannot open shared object file: No such file or directory
Error running filter pandoc-include:
Filter returned error status 127
```
I do have this file on my system however, but as a newer version:
```bash
$ locate libHSpandoc-types
/usr/lib/libHSpandoc-types-1.17.5.4-8Iu0ZQ3DY7ZCF41XD1ccvX-ghc8.6.5.so
```
This seems more likely to be a problem in my installation, although I'm not really sure how. I installed pandoc-include from the Arch Linux AUR (and pip, for that matter). I've already tried reinstalled a lot of the dependencies of this filter, in case something went   wrong during linking.

**Comment by rien333** [comment]
Nvm, I fixed it. Really not sure how, except that I removed a similarily named package named `pandoc-include-code`. Maybe there is a conflict?

**Comment by DCsunset** [comment]
It seems that `pandoc-include-code` is installed by cabel instead of pip, which may depend on different versions of the pandoc library.
Since I'm using `panflute` to write the filter, there may be a conflict between `panflute` and `pandoc-include-code` that causes this error.
