### ISSUE TITLE
files with _ (underscore) in their name

### ISSUE THREAD

**Issue by faridcher** [DCsunset/pandoc-include#31]
works fine with normal filenames but 
```merkdown
```py
!include sound/__init__.py
‌‍```
```

does nothing: 
![image](https://user-images.githubusercontent.com/9982519/213825177-db392b9a-7316-4e7c-a2da-70c4f781ed28.png)

**Comment by DCsunset** [comment]
Hi, for filenames with special sequence in Markdown language, you can use the following syntax to escape them:

```
!include `__init__.py`
```

I have updated README for such cases.
