### ISSUE TITLE
No longer automatically inserting pagebreaks

### ISSUE THREAD

**Issue by orjanv** [DCsunset/pandoc-include#32]
I recently changed laptop for writing and set up my writing environment, now running pandoc-include 1.2.0 and pandoc 3.0.1.

When I included .md-files in a main one, I didn't need to include pagebreaks for each chapter of my book, which are in separate .md-files. Now I have to do this for it to work:

```
\pagebreak

!include forord.md

\pagebreak

!include 01.md

\pagebreak

```
Anything I have missed?

**Comment by DCsunset** [comment]
Hi, I just tried pandoc 3.0.1 and inserted a page break at the end of the included file and it seems working. Can you provide a minimum markdown file to reproduce the problem?

**Comment by orjanv** [comment]
Late followup, but it seems to work fine now without the \pagebreak commands.
