### ISSUE TITLE
Non english characters are not processed correctly

### ISSUE THREAD

**Issue by ikalogic** [DCsunset/pandoc-include#4]
If I have these spanish words in my main *.md file:
`Descripción del producto`
It gets correctly converted to PDF.

However, if these same words are included and hence processed by the pandoc-include filter, I get this result in the PDF:

`DescripciÃ³n del producto`

As you can see, that special "o" character got messed up. Any idea how to prevent this?

If this can work, it will save me a lot of time!

Thanks!

**Comment by ikalogic** [comment]
The workaround i have found for the moment is to html'escpae the text in the included *.md files.
it's works, but the modified files are barely readable...

**Comment by DCsunset** [comment]
It seems a bug of this filter.
I may try to fix it later, and it may take some time.

**Comment by ikalogic** [comment]
Thank you very much, as I said, there is workaround, so it's not urgent :)

**Comment by DCsunset** [comment]
I tried it myself, but couldn't reproduce the problem.
Could you provide a simple example and your options to compile?

**Comment by mario45211** [comment]
Same problem for me. 
@DCsunset - to reproduce, try to use some language specific character in file to include and then try to include its to root file.

**Comment by DCsunset** [comment]
Fix this issue thanks to @mario45211 .
