### ISSUE TITLE
Release 1.3.1 not available in Pypi

### ISSUE THREAD

**Issue by ShiiFu** [DCsunset/pandoc-include#51]
Latest available release on [PiPy](https://pypi.org/project/pandoc-include/#history) is 1.3.0. Version 1.3.1 is not available.

Release was not pushed by [latest GitHub Action](https://github.com/DCsunset/pandoc-include/actions/runs/8499186725/job/23279714144) because Action tried to push version 1.3.0 which already exist.

```
WARNING  Skipping pandoc_include-1.3.0-py3-none-any.whl because it appears to   
         already exist                                                          
WARNING  Skipping pandoc-include-1.3.0.tar.gz because it appears to already     
         exist    
``` 

May be the error come from `setup.py` file which still declare version 1.3.0: 
https://github.com/DCsunset/pandoc-include/blob/1d293555503f21072fdee7aa4e648235207b3471/setup.py#L4

Bump this version could fix the issue.

--- 

My original problem was because pandoc-include version 1.3.0 is not compatible with latest Pandoc release 3.2.
Full error log if needed: 
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/pandoc-include", line 5, in <module>
    from pandoc_include.main import main
  File "/opt/homebrew/lib/python3.11/site-packages/pandoc_include/main.py", line 11, in <module>
    import panflute as pf
  File "/Users/user/Library/Python/3.11/lib/python/site-packages/panflute/__init__.py", line 40, in <module>
    from .autofilter import main, panfl, get_filter_dirs, stdio
  File "/Users/user/Library/Python/3.11/lib/python/site-packages/panflute/autofilter.py", line 13, in <module>
    import click
ModuleNotFoundError: No module named 'click'
Error running filter pandoc-include:
Filter returned error status 1
```

Workaround is to install with one of the following `pip install` instruction

```sh
pip install --upgrade --force --no-cache git+https://github.com/DCsunset/pandoc-include@v1.3.1
# or current dev version from Readme:
pip install --upgrade --force --no-cache git+https://github.com/DCsunset/pandoc-include
```

Thank you for your work on this project.

I can open a PR is needed.

**Comment by DCsunset** [comment]
Yes you are right. It seems that the version wasn't updated correctly last time. Since there are some other fixes as well, I've bumped it to v1.3.2. This issue should be resolved.
