### ISSUE TITLE
Any way to pass options to the executed pandoc?

### ISSUE THREAD

**Issue by ma10** [DCsunset/pandoc-include#7]
I execute pandoc with several options to controll the resulting format, etc.

So far, however, I haven't found any way to pass the same options to the executed pandoc via pandoc-include.

This will make some inconsistency in resulting files, between the including and the included files.

It would be extremely useful if I could list options to be passed to the child process in the header of files to be included, for example.

**Comment by DCsunset** [comment]
This feature has been added in v0.7.0.
You could use `pandoc-options` to specify the pandoc options for included files.

See https://github.com/DCsunset/pandoc-include#header-options

**Comment by ma10** [comment]
Ooop, I was looking at locally checked-out copy, which was not the latest.

This should be very useful!!

Thanks.

**Comment by DCsunset** [comment]
Feel free to open a new issue if you find some bugs in it.
